"""Spike: the full alarm chain, with an audible beep on every confirmed alarm.

Deliberately asymmetric tuning, which is the whole idea of the design:

  MOTION STAGE  - as sensitive as we can make it. Catch the smallest twitch.
                  Cheap, so over-triggering costs almost nothing.
  ALARM STAGE   - strict. A motion blob only becomes an alarm if the detector
                  calls it person/vehicle in K of the last M analysed frames on
                  the same track, and the track has lived long enough.

Parked cars never move, so they never produce a blob and never reach the
detector at all. Rain, leaves and shadows do produce blobs, but fail the
classification and N-of-M gates.

The output video has an audio track: a high beep when a person alarm fires,
a low beep for a vehicle. Watch it with sound to get a feel for the alarm rate.

Usage:
    uv run python spike/alarm_demo.py footage/clip.mov
    uv run python spike/alarm_demo.py footage/clip.mov --need 3 --window 5 --conf 0.25
"""

from __future__ import annotations

import argparse
import json
import math
import subprocess
import time
import wave
from collections import Counter, deque
from pathlib import Path

import cv2
import numpy as np

PERSON = {"person"}
VEHICLE = {"car", "truck", "bus", "motorcycle", "bicycle", "train"}
WANTED = PERSON | VEHICLE

GREEN = (0, 255, 0)
BLUE = (255, 160, 0)
YELLOW = (0, 220, 220)
CYAN = (255, 255, 0)
RED = (0, 0, 255)
WHITE = (255, 255, 255)
GREY = (130, 130, 130)  # detection rejected for sitting on static pixels

SAMPLE_RATE = 22050


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Motion-gated detection with confirmed alarms")
    parser.add_argument("video")
    parser.add_argument("--model", default="yolo11n.pt")
    parser.add_argument("--out", default="")

    sensitivity = parser.add_argument_group("motion stage (keep this sensitive)")
    sensitivity.add_argument("--scale", type=float, default=0.25)
    sensitivity.add_argument("--var-threshold", type=float, default=10.0, help="lower = more sensitive")
    sensitivity.add_argument("--min-blob-area", type=int, default=6, help="min blob area, downscaled px")
    sensitivity.add_argument("--dilate", type=int, default=2)
    sensitivity.add_argument("--global-motion-frac", type=float, default=0.35)

    strictness = parser.add_argument_group("alarm stage (keep this strict)")
    strictness.add_argument("--conf", type=float, default=0.25, help="detector confidence threshold")
    strictness.add_argument("--need", type=int, default=3, help="K: detections required")
    strictness.add_argument("--window", type=int, default=5, help="M: out of the last M analysed frames")
    strictness.add_argument("--min-track-age", type=int, default=3, help="analysed frames a track must live")
    strictness.add_argument("--cooldown", type=float, default=4.0, help="seconds between alarms per class")
    strictness.add_argument(
        "--min-motion-overlap",
        type=float,
        default=0.15,
        help="fraction of the detection box that must sit on moving pixels; 0 disables",
    )

    runtime = parser.add_argument_group("runtime")
    runtime.add_argument("--crop-imgsz", type=int, default=320)
    runtime.add_argument("--stride", type=int, default=3)
    runtime.add_argument("--pad", type=float, default=1.8)
    runtime.add_argument("--min-crop", type=int, default=112)
    runtime.add_argument("--max-crops", type=int, default=10)
    runtime.add_argument("--warmup", type=int, default=15)
    runtime.add_argument("--max-frames", type=int, default=0)
    return parser.parse_args()


def merge_boxes(boxes, gap):
    """Union boxes that overlap once inflated by `gap`, so one target yields one crop."""
    merged: list[list[int]] = []
    for x, y, w, h in boxes:
        box = [x, y, x + w, y + h]
        for existing in merged:
            if (
                box[0] - gap < existing[2]
                and existing[0] - gap < box[2]
                and box[1] - gap < existing[3]
                and existing[1] - gap < box[3]
            ):
                existing[0] = min(existing[0], box[0])
                existing[1] = min(existing[1], box[1])
                existing[2] = max(existing[2], box[2])
                existing[3] = max(existing[3], box[3])
                break
        else:
            merged.append(box)
    return [(b[0], b[1], b[2] - b[0], b[3] - b[1]) for b in merged]


def motion_overlap(det_box, motion_boxes) -> float:
    """Fraction of the detection box covered by moving regions.

    Without this, a crop generated by a person walking past a parked car also
    contains the car, the detector labels the car, and scenery raises an alarm.
    """
    x1, y1, x2, y2 = det_box
    det_area = max((x2 - x1) * (y2 - y1), 1)
    covered = 0
    for mx, my, mw, mh in motion_boxes:
        ix1, iy1 = max(x1, mx), max(y1, my)
        ix2, iy2 = min(x2, mx + mw), min(y2, my + mh)
        if ix2 > ix1 and iy2 > iy1:
            covered += (ix2 - ix1) * (iy2 - iy1)
    return min(covered / det_area, 1.0)


def to_crop_rect(box, frame_w, frame_h, pad, min_side):
    x, y, w, h = box
    cx, cy = x + w // 2, y + h // 2
    side = min(max(int(max(w, h) * pad), min_side), frame_w, frame_h)
    half = side // 2
    return min(max(cx - half, 0), frame_w - side), min(max(cy - half, 0), frame_h - side), side


class Track:
    """One candidate object followed across analysed frames."""

    __slots__ = ("id", "cx", "cy", "box", "hits", "age", "misses", "classes", "best_conf", "alarmed")

    def __init__(self, track_id, box, label, conf, window):
        self.id = track_id
        self.box = box
        self.cx = (box[0] + box[2]) / 2
        self.cy = (box[1] + box[3]) / 2
        self.hits = deque(maxlen=window)
        self.hits.append(1)
        self.age = 1
        self.misses = 0
        self.classes = Counter({label: 1})
        self.best_conf = conf
        self.alarmed = False

    def update(self, box, label, conf):
        self.box = box
        self.cx = (box[0] + box[2]) / 2
        self.cy = (box[1] + box[3]) / 2
        self.hits.append(1)
        self.age += 1
        self.misses = 0
        self.classes[label] += 1
        self.best_conf = max(self.best_conf, conf)

    def miss(self):
        self.hits.append(0)
        self.age += 1
        self.misses += 1

    @property
    def label(self):
        return self.classes.most_common(1)[0][0]

    def confirmed(self, need, min_age):
        return sum(self.hits) >= need and self.age >= min_age


def beep(frequency, duration_s, volume=0.35):
    t = np.linspace(0, duration_s, int(SAMPLE_RATE * duration_s), endpoint=False)
    tone = np.sin(2 * math.pi * frequency * t)
    envelope = np.minimum(1.0, np.minimum(t, duration_s - t) * 60.0)  # short fade in/out
    return (tone * envelope * volume).astype(np.float32)


def write_alarm_track(path: Path, events, duration_s):
    """Render a mono WAV with a beep at each alarm time."""
    audio = np.zeros(int(SAMPLE_RATE * duration_s) + SAMPLE_RATE, np.float32)
    person_beep = beep(1200, 0.18)
    vehicle_beep = beep(500, 0.18)
    for at_second, label in events:
        tone = person_beep if label in PERSON else vehicle_beep
        start = int(at_second * SAMPLE_RATE)
        audio[start : start + len(tone)] += tone
    audio = np.clip(audio, -1.0, 1.0)
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SAMPLE_RATE)
        handle.writeframes((audio * 32767).astype(np.int16).tobytes())


def mux(video_path: Path, audio_path: Path, out_path: Path) -> bool:
    command = [
        "ffmpeg", "-y", "-loglevel", "error",
        "-i", str(video_path), "-i", str(audio_path),
        "-c:v", "copy", "-c:a", "aac", "-shortest", str(out_path),
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode:
        print("ffmpeg failed:", result.stderr.strip()[:400])
        return False
    return True


def main() -> int:
    args = parse_args()
    video = Path(args.video)
    if not video.exists():
        print(f"video not found: {video}")
        return 1

    from ultralytics import YOLO

    print(f"loading model {args.model} ...")
    model = YOLO(args.model)
    names = model.names

    capture = cv2.VideoCapture(str(video))
    if not capture.isOpened():
        print(f"could not open video: {video}")
        return 1

    frame_w = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_h = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
    src_fps = capture.get(cv2.CAP_PROP_FPS) or 30.0
    out_fps = max(src_fps / args.stride, 1.0)
    total = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
    match_distance = 0.06 * math.hypot(frame_w, frame_h)

    print(f"video: {frame_w}x{frame_h} @ {src_fps:.2f} fps, {total} frames")
    print(f"motion : var_threshold={args.var_threshold} min_blob_area={args.min_blob_area} (sensitive)")
    print(f"alarm  : conf={args.conf} need {args.need} of {args.window} frames, "
          f"min age {args.min_track_age}, cooldown {args.cooldown}s (strict)\n")

    out_path = Path(args.out) if args.out else video.with_name(video.stem + "_alarm.mp4")
    silent_path = out_path.with_name(out_path.stem + "_silent.mp4")
    audio_path = out_path.with_name(out_path.stem + "_beeps.wav")
    writer = cv2.VideoWriter(
        str(silent_path), cv2.VideoWriter_fourcc(*"mp4v"), out_fps, (frame_w, frame_h)
    )

    def new_subtractor():
        return cv2.createBackgroundSubtractorMOG2(
            history=500, varThreshold=args.var_threshold, detectShadows=True
        )

    subtractor = new_subtractor()
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))

    tracks: list[Track] = []
    next_track_id = 1
    alarms: list[tuple[float, str]] = []
    last_alarm_at: dict[str, float] = {}

    processed = analysed = 0
    frames_with_motion = frames_suppressed = crops_total = 0
    raw_detections = 0
    static_rejects = 0
    static_reject_classes: Counter[str] = Counter()
    class_counts: Counter[str] = Counter()
    motion_ms: list[float] = []
    detect_ms: list[float] = []
    flash_until = -1
    source_index = -1

    while True:
        ok, image = capture.read()
        if not ok:
            break
        source_index += 1
        if source_index % args.stride:
            continue
        processed += 1
        out_time = (processed - 1) / out_fps

        # --- motion stage: sensitive -------------------------------------
        started = time.perf_counter()
        small = cv2.resize(image, None, fx=args.scale, fy=args.scale, interpolation=cv2.INTER_AREA)
        gray = cv2.cvtColor(small, cv2.COLOR_BGR2GRAY)
        mask = subtractor.apply(gray)
        mask[mask < 255] = 0
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
        mask = cv2.dilate(mask, kernel, iterations=args.dilate)
        moving_frac = float(np.count_nonzero(mask)) / mask.size
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        raw_boxes = []
        for contour in contours:
            if cv2.contourArea(contour) < args.min_blob_area:
                continue
            x, y, w, h = cv2.boundingRect(contour)
            raw_boxes.append(
                (int(x / args.scale), int(y / args.scale), int(w / args.scale), int(h / args.scale))
            )
        motion_ms.append((time.perf_counter() - started) * 1000.0)

        suppressed = moving_frac > args.global_motion_frac
        if suppressed:
            frames_suppressed += 1
            subtractor = new_subtractor()
            raw_boxes = []

        warming = processed <= args.warmup
        boxes = [] if warming else merge_boxes(raw_boxes, gap=int(0.02 * frame_w))
        boxes.sort(key=lambda b: b[2] * b[3], reverse=True)
        boxes = boxes[: args.max_crops]
        if boxes:
            frames_with_motion += 1

        # --- classification stage: strict --------------------------------
        crops, rects = [], []
        for box in boxes:
            left, top, side = to_crop_rect(box, frame_w, frame_h, args.pad, args.min_crop)
            crops.append(image[top : top + side, left : left + side].copy())
            rects.append((left, top, side))
        crops_total += len(crops)

        detections = []
        if crops:
            started = time.perf_counter()
            results = model.predict(
                crops, imgsz=args.crop_imgsz, conf=args.conf, verbose=False, device="cpu"
            )
            detect_ms.append((time.perf_counter() - started) * 1000.0)
            for result, (left, top, _side) in zip(results, rects):
                for det in result.boxes:
                    label = names[int(det.cls)]
                    if label not in WANTED:
                        continue
                    # Ultralytics already rescales boxes to the crop's own pixel
                    # coordinates, so only the crop offset has to be added back.
                    x1, y1, x2, y2 = (float(v) for v in det.xyxy[0])
                    box = (int(left + x1), int(top + y1), int(left + x2), int(top + y2))
                    detections.append((label, float(det.conf), box))
        else:
            detect_ms.append(0.0)
        raw_detections += len(detections)
        for label, _, _ in detections:
            class_counts[label] += 1

        # Gate: the detected object must itself be moving, not just share a crop
        # with something that is.
        if args.min_motion_overlap > 0:
            kept = []
            for label, confidence, box in detections:
                if motion_overlap(box, raw_boxes) >= args.min_motion_overlap:
                    kept.append((label, confidence, box))
                else:
                    static_rejects += 1
                    static_reject_classes[label] += 1
                    cv2.rectangle(image, (box[0], box[1]), (box[2], box[3]), GREY, 1)
            detections = kept

        if not warming:
            analysed += 1

        # --- tracking and N-of-M confirmation ----------------------------
        unmatched = list(detections)
        for track in tracks:
            best, best_distance = None, match_distance
            for detection in unmatched:
                _, _, box = detection
                distance = math.hypot((box[0] + box[2]) / 2 - track.cx, (box[1] + box[3]) / 2 - track.cy)
                if distance < best_distance:
                    best, best_distance = detection, distance
            if best is None:
                track.miss()
            else:
                unmatched.remove(best)
                track.update(best[2], best[0], best[1])
        for label, confidence, box in unmatched:
            tracks.append(Track(next_track_id, box, label, confidence, args.window))
            next_track_id += 1
        tracks = [t for t in tracks if t.misses <= args.window]

        fired = []
        for track in tracks:
            if track.alarmed or not track.confirmed(args.need, args.min_track_age):
                continue
            label = track.label
            if out_time - last_alarm_at.get(label, -1e9) < args.cooldown:
                continue
            track.alarmed = True
            last_alarm_at[label] = out_time
            alarms.append((out_time, label))
            fired.append(track)

        if fired:
            flash_until = processed + int(out_fps)

        # --- draw ---------------------------------------------------------
        for x, y, w, h in raw_boxes:
            cv2.rectangle(image, (x, y), (x + w, y + h), YELLOW, 1)
        for left, top, side in rects:
            cv2.rectangle(image, (left, top), (left + side, top + side), CYAN, 1)
        for track in tracks:
            x1, y1, x2, y2 = track.box
            if track.alarmed:
                colour, thickness = (GREEN if track.label in PERSON else BLUE), 4
                caption = f"ALARM {track.label} {track.best_conf:.2f} #{track.id}"
            else:
                colour, thickness = WHITE, 2
                caption = f"{track.label} {sum(track.hits)}/{args.window} #{track.id}"
            cv2.rectangle(image, (x1, y1), (x2, y2), colour, thickness)
            cv2.putText(image, caption, (x1, max(y1 - 8, 18)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, colour, 2, cv2.LINE_AA)

        banner = (f"f{source_index} blobs={len(raw_boxes)} crops={len(crops)} "
                  f"det={len(detections)} tracks={len(tracks)} alarms={len(alarms)}")
        if warming:
            banner = "WARMUP " + banner
        if suppressed:
            banner = "GLOBAL-MOTION SUPPRESSED " + banner
        cv2.putText(image, banner, (10, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8,
                    RED if suppressed else WHITE, 2, cv2.LINE_AA)
        if processed <= flash_until:
            cv2.rectangle(image, (0, 0), (frame_w - 1, frame_h - 1), RED, 12)
            cv2.putText(image, "ALARM", (int(frame_w * 0.32), 110),
                        cv2.FONT_HERSHEY_SIMPLEX, 2.0, RED, 5, cv2.LINE_AA)
        writer.write(image)

        if processed % 50 == 0:
            print(f"  {processed} frames, {len(alarms)} alarms, {crops_total} crops")
        if args.max_frames and processed >= args.max_frames:
            break

    capture.release()
    writer.release()

    if not analysed:
        print("no frames analysed")
        return 1

    duration_s = processed / out_fps
    write_alarm_track(audio_path, alarms, duration_s)
    final = out_path if mux(silent_path, audio_path, out_path) else silent_path

    # Machine-readable alarms, so spike/score.py can grade this run against
    # hand-made ground truth. Alarm times share the source clip's timeline.
    alarms_path = out_path.with_suffix(".alarms.json")
    alarms_path.write_text(
        json.dumps(
            {
                "video": str(video),
                "duration": round(duration_s, 2),
                "settings": {
                    "conf": args.conf,
                    "need": args.need,
                    "window": args.window,
                    "min_track_age": args.min_track_age,
                    "cooldown": args.cooldown,
                    "min_motion_overlap": args.min_motion_overlap,
                    "var_threshold": args.var_threshold,
                    "min_blob_area": args.min_blob_area,
                    "stride": args.stride,
                    "crop_imgsz": args.crop_imgsz,
                },
                "alarms": [{"at": round(t, 2), "label": label} for t, label in alarms],
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    def median(values):
        ordered = sorted(values)
        return ordered[len(ordered) // 2] if ordered else 0.0

    total_ms = [m + d for m, d in zip(motion_ms, detect_ms)]
    person_alarms = sum(1 for _, label in alarms if label in PERSON)

    print("\n--- results ---")
    print(f"frames analysed         : {analysed}")
    print(f"frames with motion      : {frames_with_motion} ({100 * frames_with_motion / analysed:.0f}%)")
    print(f"frames global-suppressed: {frames_suppressed}")
    print(f"crops per analysed frame: {crops_total / analysed:.1f}")
    print(f"raw detections          : {raw_detections}  {dict(class_counts) or ''}")
    print(f"rejected as static      : {static_rejects}  {dict(static_reject_classes) or ''}")
    print(f"CONFIRMED ALARMS        : {len(alarms)}  (person {person_alarms}, vehicle {len(alarms) - person_alarms})")
    if alarms:
        listed = ", ".join(f"{t:.1f}s {label}" for t, label in alarms[:25])
        print(f"alarm times (output clip): {listed}{' ...' if len(alarms) > 25 else ''}")
    print(f"motion gate median      : {median(motion_ms):.0f} ms")
    print(f"detector median         : {median(detect_ms):.0f} ms")
    print(f"total median            : {median(total_ms):.0f} ms  ({1000 / max(median(total_ms), 1):.1f} fps)")
    print(f"\nvideo with alarm beeps  : {final}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
